### ISSUE TITLE
ArgumentError when initializing Formatador

### ISSUE THREAD

**Issue by kshlm** [fog/fog-core#123]
I use the vagrant-libvirt plugin, which uses the Fog library. I get this error when I'm trying to launch a vm.
```
/home/kaushal/.vagrant.d/gems/gems/fog-core-1.27.3/lib/fog/formatador.rb:6:in `initialize': wrong number of arguments (0 for 1) (ArgumentError)
        from /home/kaushal/.vagrant.d/gems/gems/fog-core-1.27.3/lib/fog/core/model.rb:24:in `new'
        from /home/kaushal/.vagrant.d/gems/gems/fog-core-1.27.3/lib/fog/core/model.rb:24:in `inspect'
        from /home/kaushal/.vagrant.d/gems/gems/fog-core-1.27.3/lib/fog/core/collection.rb:19:in `inspect'
        from /home/kaushal/.vagrant.d/gems/gems/fog-core-1.27.3/lib/fog/core/collection.rb:19:in `to_s'
        from /home/kaushal/.vagrant.d/gems/gems/vagrant-libvirt-0.0.24/lib/vagrant-libvirt/action/set_name_of_domain.rb:17:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builtin/call.rb:53:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
        from /home/kaushal/.vagrant.d/gems/gems/vagrant-libvirt-0.0.24/lib/vagrant-libvirt/action/connect_libvirt.rb:18:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/machine.rb:212:in `action_raw'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/machine.rb:189:in `block in action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/environment.rb:516:in `lock'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/machine.rb:176:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/machine.rb:176:in `action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```
My environment:
ruby 2.2.0p0
vagrant 1.7.2
vagrant-libvirt 0.0.24
fog 1.27.0

I reported this as issue https://github.com/pradels/vagrant-libvirt/issues/292 on vagrant-libvirt, but I was asked to open a new issue here.

I can reproduce the same with the following snippet of code,
```ruby
require "fog"
lv = Fog::Compute.new({:provider => 'Libvirt'})
lv.servers.all.to_s
```
this leads to the same error,
```
/home/kaushal/.gem/ruby/2.2.0/gems/fog-core-1.27.3/lib/fog/formatador.rb:6:in `initialize': wrong number of arguments (0 for 1) (ArgumentError)
        from /home/kaushal/.gem/ruby/2.2.0/gems/fog-core-1.27.3/lib/fog/core/model.rb:24:in `new'
        from /home/kaushal/.gem/ruby/2.2.0/gems/fog-core-1.27.3/lib/fog/core/model.rb:24:in `inspect'
        from /home/kaushal/.gem/ruby/2.2.0/gems/fog-core-1.27.3/lib/fog/core/collection.rb:19:in `inspect'
        from /home/kaushal/.gem/ruby/2.2.0/gems/fog-core-1.27.3/lib/fog/core/collection.rb:19:in `to_s'
        from test.rb:4:in `<main>'
```

**Comment by plribeiro3000** [comment]
This seems a duplicate of #122 which was already solved.

@kshlm Could you try this out against master of the repo?

**Comment by kshlm** [comment]
@plribeiro3000 The reporter of #122 closed it himself, not as a response to a fix. So does master have a fix for it or not?

**Comment by kshlm** [comment]
Okay. Just saw that #120 fixes this. I'll close this issue then. Thanks @plribeiro3000.
