### ISSUE TITLE
TypeError: no implicit conversion of Symbol into Integer

### ISSUE THREAD

**Issue by jasecoop** [fog/fog-core#159]
Hi

I'm trying to get my app working on Heroku and I'm recieving this error in the server logs around the credentials

```
2015-08-13T13:09:43.384364+00:00 heroku[web.1]: Starting process with command `bin/rails server -p 59829 -e production`
2015-08-13T13:09:48.324529+00:00 app[web.1]: => Rails 4.2.1 application starting in production on http://0.0.0.0:59829
2015-08-13T13:09:48.324531+00:00 app[web.1]: => Run `rails server -h` for more startup options
2015-08-13T13:09:48.324502+00:00 app[web.1]: => Booting Puma
2015-08-13T13:09:48.324532+00:00 app[web.1]: => Ctrl-C to shutdown server
2015-08-13T13:09:48.622540+00:00 app[web.1]: Exiting
2015-08-13T13:09:48.622587+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/fog-core-1.29.0/lib/fog/core/credentials.rb:71:in `[]': no implicit conversion of Symbol into Integer (TypeError)
2015-08-13T13:09:48.622594+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/fog-core-1.29.0/lib/fog/core/service.rb:122:in `fetch_credentials'
2015-08-13T13:09:48.622591+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/fog-core-1.29.0/lib/fog/core/credentials.rb:71:in `credentials'
2015-08-13T13:09:48.622596+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/fog-aws-0.1.1/lib/fog/aws/credential_fetcher.rb:29:in `fetch_credentials'
2015-08-13T13:09:48.622607+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/fog-core-1.29.0/lib/fog/core/service.rb:266:in `handle_settings'
2015-08-13T13:09:48.622610+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/fog-core-1.29.0/lib/fog/storage.rb:25:in `new'
2015-08-13T13:09:48.622609+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/fog-core-1.29.0/lib/fog/core/service.rb:98:in `new'
2015-08-13T13:09:48.622612+00:00 app[web.1]: 	from /app/config/initializers/fog.rb:1:in `<top (required)>'
```

I am setting Fogs credentials in config/intitializers/fog.rb

```
::FOG = Fog::Storage.new({
  :provider              =>'AWS',
  :aws_access_key_id     =>ENV['AWS_ACCESS_KEY_ID'],
  :aws_secret_access_key =>ENV['AWS_SECRET_ACCESS_KEY']
})
```

I'm at a bit of a loss was hoping somebody would be able to shed some light on my problem.

Thanks

**Comment by plribeiro3000** [comment]
I can see that you are using an old release. Can you try to use the latest version? 

https://rubygems.org/gems/fog-core

**Comment by jasecoop** [comment]
I'm using fog-core via the Fog gem. It seems the latest version is specified in my Gemfile.lock. Yet the older version runs in Heroku according to the logs. 

```
GEM
  remote: https://rubygems.org/
  specs:
    CFPropertyList (2.3.1)
    actionmailer (4.2.1)
      actionpack (= 4.2.1)
      actionview (= 4.2.1)
      activejob (= 4.2.1)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.1)
      actionview (= 4.2.1)
      activesupport (= 4.2.1)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.1)
    actionview (4.2.1)
      activesupport (= 4.2.1)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.1)
    activejob (4.2.1)
      activesupport (= 4.2.1)
      globalid (>= 0.3.0)
    activemodel (4.2.1)
      activesupport (= 4.2.1)
      builder (~> 3.1)
    activerecord (4.2.1)
      activemodel (= 4.2.1)
      activesupport (= 4.2.1)
      arel (~> 6.0)
    activesupport (4.2.1)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    acts-as-taggable-on (3.5.0)
      activerecord (>= 3.2, < 5)
    arel (6.0.0)
    aws-sdk (2.1.13)
      aws-sdk-resources (= 2.1.13)
    aws-sdk-core (2.1.13)
      jmespath (~> 1.0)
    aws-sdk-resources (2.1.13)
      aws-sdk-core (= 2.1.13)
    bcrypt (3.1.10)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    browserify-rails (0.9.3)
      sprockets (~> 2.2)
    builder (3.2.2)
    byebug (5.0.0)
      columnize (= 0.9.0)
    carrierwave (0.10.0)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
      json (>= 1.7)
      mime-types (>= 1.16)
    coffee-rails (4.1.0)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.9.1.1)
    columnize (0.9.0)
    connection_pool (2.2.0)
    debug_inspector (0.0.2)
    devise (3.5.1)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      responders
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    dotenv (2.0.1)
    dotenv-rails (2.0.1)
      dotenv (= 2.0.1)
    dropzonejs-rails (0.7.1)
      rails (> 3.1)
    erubis (2.7.0)
    excon (0.45.4)
    execjs (2.5.2)
    fission (0.5.0)
      CFPropertyList (~> 2.2)
    fog (1.33.0)
      fog-atmos
      fog-aws (>= 0.6.0)
      fog-brightbox (~> 0.4)
      fog-core (~> 1.32)
      fog-dynect
      fog-ecloud (= 0.1.1)
      fog-google (>= 0.0.2)
      fog-json
      fog-local
      fog-powerdns (>= 0.1.1)
      fog-profitbricks
      fog-radosgw (>= 0.0.2)
      fog-riakcs
      fog-sakuracloud (>= 0.0.4)
      fog-serverlove
      fog-softlayer
      fog-storm_on_demand
      fog-terremark
      fog-vmfusion
      fog-voxel
      fog-xml (~> 0.1.1)
      ipaddress (~> 0.5)
      nokogiri (~> 1.5, >= 1.5.11)
    fog-atmos (0.1.0)
      fog-core
      fog-xml
    fog-aws (0.7.3)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
      ipaddress (~> 0.8)
    fog-brightbox (0.7.1)
      fog-core (~> 1.22)
      fog-json
      inflecto (~> 0.0.2)
    fog-core (1.32.0)
      builder
      excon (~> 0.45)
      formatador (~> 0.2)
      mime-types
      net-scp (~> 1.1)
      net-ssh (>= 2.1.3)
    fog-dynect (0.0.1)
      fog-core
      fog-json
      fog-xml
    fog-ecloud (0.1.1)
      fog-core
      fog-xml
    fog-google (0.0.7)
      fog-core
      fog-json
      fog-xml
    fog-json (1.0.0)
      multi_json (~> 1.0)
    fog-local (0.2.1)
      fog-core (~> 1.27)
    fog-powerdns (0.1.1)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
    fog-profitbricks (0.0.2)
      fog-core
      fog-xml
      nokogiri
    fog-radosgw (0.0.3)
      fog-core (>= 1.21.0)
      fog-json
      fog-xml (>= 0.0.1)
    fog-riakcs (0.1.0)
      fog-core
      fog-json
      fog-xml
    fog-sakuracloud (1.0.0)
      fog-core
      fog-json
    fog-serverlove (0.1.1)
      fog-core
      fog-json
    fog-softlayer (0.4.1)
      fog-core
      fog-json
    fog-storm_on_demand (0.1.0)
      fog-core
      fog-json
    fog-terremark (0.0.4)
      fog-core
      fog-xml
    fog-vmfusion (0.0.1)
      fission
      fog-core
    fog-voxel (0.0.2)
      fog-core
      fog-xml
    fog-xml (0.1.1)
      fog-core
      nokogiri (~> 1.5, >= 1.5.11)
    formatador (0.2.5)
    globalid (0.3.5)
      activesupport (>= 4.1.0)
    haml (4.0.6)
      tilt
    hike (1.2.3)
    i18n (0.7.0)
    inflecto (0.0.2)
    ipaddress (0.8.0)
    jbuilder (2.3.0)
      activesupport (>= 3.0.0, < 5)
      multi_json (~> 1.2)
    jmespath (1.0.2)
      multi_json (~> 1.0)
    jquery-rails (4.0.4)
      rails-dom-testing (~> 1.0)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    json (1.8.3)
    loofah (2.0.2)
      nokogiri (>= 1.5.9)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    mime-types (2.6.1)
    mini_portile (0.6.2)
    minitest (5.7.0)
    multi_json (1.11.1)
    net-scp (1.2.1)
      net-ssh (>= 2.6.5)
    net-ssh (2.9.2)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    orm_adapter (0.5.0)
    pg (0.18.2)
    puma (2.11.3)
      rack (>= 1.1, < 2.0)
    rack (1.6.2)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.1)
      actionmailer (= 4.2.1)
      actionpack (= 4.2.1)
      actionview (= 4.2.1)
      activejob (= 4.2.1)
      activemodel (= 4.2.1)
      activerecord (= 4.2.1)
      activesupport (= 4.2.1)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.1)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.6)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.2)
      loofah (~> 2.0)
    rails_12factor (0.0.3)
      rails_serve_static_assets
      rails_stdout_logging
    rails_serve_static_assets (0.0.4)
    rails_stdout_logging (0.0.3)
    railties (4.2.1)
      actionpack (= 4.2.1)
      activesupport (= 4.2.1)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (10.4.2)
    rdoc (4.2.0)
    react-rails (1.0.0)
      coffee-script-source (~> 1.8)
      connection_pool
      execjs
      rails (>= 3.1)
      react-source (~> 0.13)
    react-router-rails (0.13.3)
      rails (>= 3.1)
      react-rails (>= 0.12)
    react-source (0.13.3)
    responders (2.1.0)
      railties (>= 4.2.0, < 5)
    sass (3.4.14)
    sass-rails (5.0.3)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (~> 1.1)
    sdoc (0.4.1)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    spring (1.3.6)
    sprockets (2.12.3)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-rails (2.3.1)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (1.4.1)
    turbolinks (2.5.3)
      coffee-rails
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.1)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    warden (1.2.3)
      rack (>= 1.0)
    web-console (2.1.3)
      activemodel (>= 4.0)
      binding_of_caller (>= 0.7.2)
      railties (>= 4.0)
      sprockets-rails (>= 2.0, < 4.0)

PLATFORMS
  ruby

DEPENDENCIES
  acts-as-taggable-on (~> 3.4)
  aws-sdk (~> 2)
  browserify-rails (~> 0.9.1)
  byebug
  carrierwave
  coffee-rails (~> 4.1.0)
  devise
  dotenv-rails
  dropzonejs-rails
  fog
  haml
  jbuilder (~> 2.0)
  jquery-rails
  pg
  puma
  rails (= 4.2.1)
  rails_12factor
  react-rails
  react-router-rails (~> 0.13.3)
  sass-rails (~> 5.0)
  sdoc (~> 0.4.0)
  spring
  turbolinks
  uglifier (>= 1.3.0)
  web-console (~> 2.0)
```

**Comment by jasecoop** [comment]
@plribeiro3000 
Updated gems. Still getting same issue...

```
2015-08-13T13:59:39.901226+00:00 heroku[web.1]: State changed from crashed to starting
2015-08-13T13:59:45.722996+00:00 heroku[web.1]: Starting process with command `bin/rails server -p 41380 -e production`
2015-08-13T13:59:49.809591+00:00 app[web.1]: => Booting Puma
2015-08-13T13:59:49.809612+00:00 app[web.1]: => Rails 4.2.1 application starting in production on http://0.0.0.0:41380
2015-08-13T13:59:49.809615+00:00 app[web.1]: => Run `rails server -h` for more startup options
2015-08-13T13:59:49.809616+00:00 app[web.1]: => Ctrl-C to shutdown server
2015-08-13T13:59:50.131428+00:00 app[web.1]: Exiting
2015-08-13T13:59:50.131475+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/fog-core-1.32.1/lib/fog/core/credentials.rb:71:in `[]': no implicit conversion of Symbol into Integer (TypeError)
2015-08-13T13:59:50.131481+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/fog-core-1.32.1/lib/fog/core/credentials.rb:71:in `credentials'
2015-08-13T13:59:50.131483+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/fog-core-1.32.1/lib/fog/core/service.rb:122:in `fetch_credentials'
2015-08-13T13:59:50.131487+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/fog-aws-0.7.4/lib/fog/aws/credential_fetcher.rb:27:in `fetch_credentials'
2015-08-13T13:59:50.131492+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/fog-core-1.32.1/lib/fog/core/service.rb:98:in `new'
2015-08-13T13:59:50.131488+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/fog-core-1.32.1/lib/fog/core/service.rb:266:in `handle_settings'
2015-08-13T13:59:50.131521+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/fog-core-1.32.1/lib/fog/core/services_mixin.rb:16:in `new'
2015-08-13T13:59:50.131522+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/fog-core-1.32.1/lib/fog/storage.rb:22:in `new'
2015-08-13T13:59:50.131524+00:00 app[web.1]: 	from /app/config/initializers/fog.rb:1:in `<top (required)>'
2015-08-13T13:59:50.131526+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
2015-08-13T13:59:50.131530+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
2015-08-13T13:59:50.131531+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
2015-08-13T13:59:50.131533+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
2015-08-13T13:59:50.131534+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
2015-08-13T13:59:50.131538+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:166:in `instrument'
2015-08-13T13:59:50.131539+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/engine.rb:651:in `load_config_initializer'
2015-08-13T13:59:50.131541+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
2015-08-13T13:59:50.131544+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/engine.rb:615:in `each'
2015-08-13T13:59:50.131546+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
2015-08-13T13:59:50.131549+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
2015-08-13T13:59:50.131551+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
2015-08-13T13:59:50.131554+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
2015-08-13T13:59:50.131555+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
2015-08-13T13:59:50.131559+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
2015-08-13T13:59:50.131566+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
2015-08-13T13:59:50.131571+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
2015-08-13T13:59:50.131572+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
2015-08-13T13:59:50.131574+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:44:in `each'
2015-08-13T13:59:50.131577+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:44:in `tsort_each_child'
2015-08-13T13:59:50.131579+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:413:in `call'
2015-08-13T13:59:50.131614+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each'
2015-08-13T13:59:50.131583+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
2015-08-13T13:59:50.131580+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
2015-08-13T13:59:50.131615+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `call'
2015-08-13T13:59:50.131618+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
2015-08-13T13:59:50.131619+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
2015-08-13T13:59:50.131620+00:00 app[web.1]: 	from /app/vendor/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
2015-08-13T13:59:50.131626+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
2015-08-13T13:59:50.131634+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
2015-08-13T13:59:50.131625+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:54:in `run_initializers'
2015-08-13T13:59:50.131635+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
2015-08-13T13:59:50.131640+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
2015-08-13T13:59:50.131627+00:00 app[web.1]: 	from /app/config/environment.rb:5:in `<top (required)>'
2015-08-13T13:59:50.131638+00:00 app[web.1]: 	from /app/config.ru:3:in `block in <main>'
2015-08-13T13:59:50.131643+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
2015-08-13T13:59:50.131629+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
2015-08-13T13:59:50.131632+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
2015-08-13T13:59:50.131645+00:00 app[web.1]: 	from /app/config.ru:in `new'
2015-08-13T13:59:50.131658+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
2015-08-13T13:59:50.131648+00:00 app[web.1]: 	from /app/config.ru:in `<main>'
2015-08-13T13:59:50.131653+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
2015-08-13T13:59:50.131656+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
2015-08-13T13:59:50.131663+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
2015-08-13T13:59:50.131667+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/commands/server.rb:61:in `app'
2015-08-13T13:59:50.131670+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
2015-08-13T13:59:50.131661+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
2015-08-13T13:59:50.131675+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/commands/server.rb:80:in `start'
2015-08-13T13:59:50.131671+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:272:in `start'
2015-08-13T13:59:50.131682+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
2015-08-13T13:59:50.131679+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:80:in `block in server'
2015-08-13T13:59:50.131689+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
2015-08-13T13:59:50.131686+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `server'
2015-08-13T13:59:50.131694+00:00 app[web.1]: 	from bin/rails:8:in `require'
2015-08-13T13:59:50.131690+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
2015-08-13T13:59:50.131697+00:00 app[web.1]: 	from bin/rails:8:in `<main>'
2015-08-13T13:59:50.989398+00:00 heroku[web.1]: State changed from starting to crashed
2015-08-13T13:59:50.975546+00:00 heroku[web.1]: Process exited with status 1
2015-08-13T14:02:10.702279+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=draggg.herokuapp.com request_id=9ec0a313-6628-4a20-bc44-d38c93d07d2e fwd="213.86.221.35" dyno= connect= service= status=503 bytes=
2015-08-13T14:02:10.918494+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=draggg.herokuapp.com request_id=4c0d4241-ab6d-4f4f-bc09-4dc2e2763dcf fwd="213.86.221.35" dyno= connect= service= status=503 bytes=
2015-08-13T14:02:11.406632+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=draggg.herokuapp.com request_id=8402fbd0-73e0-4136-8c25-c916772416d6 fwd="213.86.221.35" dyno= connect= service= status=503 bytes=
2015-08-13T14:02:12.214137+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=draggg.herokuapp.com request_id=c5972842-a5b8-4451-8ccd-ff3a2a5fe1b4 fwd="162.243.24.21" dyno= connect= service= status=503 bytes=
2015-08-13T14:02:12.288093+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=draggg.herokuapp.com request_id=b0413855-ac39-4496-bac2-fb1d4a712156 fwd="213.86.221.35" dyno= connect= service= status=503 bytes=
2015-08-13T14:02:12.689867+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=draggg.herokuapp.com request_id=676e369a-df05-4a19-b6c1-ecf5d978dab3 fwd="213.86.221.35" dyno= connect= service= status=503 bytes=
```

**Comment by plribeiro3000** [comment]
After taking a look [here](https://github.com/fog/fog-core/blob/v1.32.1/lib/fog/core/credentials.rb#L71) it seems the issue might be related to your `yaml` file. Could you paste its structure here?

**Comment by jasecoop** [comment]
@plribeiro3000 Ah, I'm without a yaml file.

What does this involve?

I have fog.rb with my credentials shown above...

**Comment by plribeiro3000** [comment]
You can see that it checks for the file so somehow it is finding a file.

https://github.com/fog/fog-core/blob/v1.32.1/lib/fog/core/credentials.rb#L69

Can you check wheter you don't have a file?

**Comment by jasecoop** [comment]
@plribeiro3000 Can't find a file.

I added .fog to my root folder and added the following but unfortunatly I'm still getting the same error. 

```
aws_access_key_id=ENV['AWS_ACCESS_KEY_ID']
aws_secret_access_key=ENV['AWS_SECRET_ACCESS_KEY']
```

**Comment by plribeiro3000** [comment]
Hmmm. It does not look at the root folder of your project but rather in the user folder.

The interesting thing is that if you don't have a file why is it finding one? Maybe is something related to your deploy or the way heroku handles it?

@geemus Can you chime in? I think you might know that better.

**Comment by geemus** [comment]
You may want to check and see if `FOG_RC` is set, as that will specify a non-default place to look for that file?

**Comment by jasecoop** [comment]
Thanks for the help guys. It's now working. You're right, it was looking for the yml file.

I added this line and it now works:

```
production:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  provider: 'AWS'
```

Thanks again for your help.

**Comment by geemus** [comment]
Great, thanks for the update.

**Comment by drKreso** [comment]
What is the benefit of being so flexible with config naming? Also eating exceptions is obfuscating the problem.
```
 rescue
     nil
 end
```

**Comment by geemus** [comment]
@drKreso It's been a while since I've worked on this particular area, so my memory may be a bit fuzzy. I think it is flexible partly due to the wide variety of config used across different providers, partly to support different use cases, and partly for ongoing backwards compatibility. It also looks like this particular issue was from several years ago. Are you having a new particular issue that I could help with?
