### ISSUE TITLE
Avoid tones of warnings

### ISSUE THREAD

**Issue by miha-plesko** [fog/fog-core#235]
We're getting tones of warnings when using fog with `bundle exec ruby -w ./demo.rb`, saying:

```
warning: method redefined; discarding old <BLABLA>
warning: previous definition of <BLABLA> was here
```

Looking at [how `attribute` utility works](https://github.com/fog/fog-core/blob/master/lib/fog/core/attributes/integer.rb#L9-L13) it seems like fog core redefines all the setters everytime we invoke it.

Q: Shouldn't fog core check if method already exists and only define setter if it doesn't exist yet, to avoid those warnings?

**Comment by plribeiro3000** [comment]
Hmm. What you suggest is a possibility but i wonder where are those methods being defined again. All attributes are supposed to be defined by `fog` so it does all the necessary logic.

Can you provide more info? Like which provider and methods did trigger this issue?

Thanks!

**Comment by plribeiro3000** [comment]
@miha-plesko I did take a look at `xlab-si/fog-vcloud-director` and it does seem that you are manually overwritting methods defined by `fog`.

I believe your issue is related to methods like [this](https://github.com/xlab-si/fog-vcloud-director/blob/bc58d09d4512ff243429a7249999f5bac16323be/lib/fog/vcloud_director/models/compute/disk.rb#L20-L31). You've defined a method setter using `fog` DSL and latter defined it again with another behavior.

Essentially you are _saving_ the object when calling a simple method setter. I would not advise that because is not a common pattern. It wouldn't be expected by the final user.

If you still want this behavior i would define the attribute using `fog` DSL as `read_only` and then define this behavior with a more suggestive name like `#update_capacity`

**Comment by miha-plesko** [comment]
Thanks for reply @plribeiro3000 . You are correct, methods like the one you linked did result in such warnings, but we managed to resolve it by manually removing the setter method prior creating it, see [here](https://github.com/xlab-si/fog-vcloud-director/blob/bc58d09d4512ff243429a7249999f5bac16323be/lib/fog/vcloud_director/models/compute/disk.rb#L18) for example.

However, even having such cases handled, warnings appear for all the attributes on any model. I mean literally, for all the attributes, even if we don't mess with the setters. After spending two days debugging I went and try [fog/openstack](https://github.com/fog/fog-openstack) gem and same warnings also appear there. Here is minimal example to reproduce for OpenStack:

```ruby
# example.rb
require 'fog/openstack'

connection_params = {
  openstack_auth_url:     "invalid",
  openstack_username:     "invalid",
  openstack_api_key:      "invalid",
  openstack_project_name: "invalid"
}
Fog::Compute::OpenStack.new(connection_params)
```

You'll be able to notice those warnings if you run with `-w` parameter like this:

```bash
$ ruby -w ./example.rb
/home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-openstack-0.1.25/lib/fog/openstack.rb:332: warning: shadowing outer local variable - service
/home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-openstack-0.1.25/lib/fog/openstack.rb:336: warning: shadowing outer local variable - service
/home/miha/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55: warning: loading in progress, circular require considered harmful - /home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-openstack-0.1.25/lib/fog/compute/openstack/models/metadata.rb
	from ./example.rb:9:in  `<main>'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-core-1.45.0/lib/fog/core/service.rb:100:in  `new'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-core-1.45.0/lib/fog/core/service.rb:137:in  `setup_requirements'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-core-1.45.0/lib/fog/core/service.rb:274:in  `require_models'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-core-1.45.0/lib/fog/core/service.rb:274:in  `each'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-core-1.45.0/lib/fog/core/service.rb:274:in  `block in require_models'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-core-1.45.0/lib/fog/core/service.rb:324:in  `require_item'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-openstack-0.1.25/lib/fog/compute/openstack/models/server.rb:2:in  `<top (required)>'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-openstack-0.1.25/lib/fog/compute/openstack/models/metadata.rb:4:in  `<top (required)>'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-openstack-0.1.25/lib/fog/compute/openstack/models/image.rb:2:in  `<top (required)>'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
/home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-openstack-0.1.25/lib/fog/compute/openstack/models/image.rb:22: warning: method redefined; discarding old metadata
/home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-core-1.45.0/lib/fog/core/attributes/default.rb:52: warning: previous definition of metadata was here
/home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-openstack-0.1.25/lib/fog/compute/openstack/models/image.rb:29: warning: method redefined; discarding old metadata=
/home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-core-1.45.0/lib/fog/core/attributes/default.rb:43: warning: previous definition of metadata= was here
/home/miha/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55: warning: loading in progress, circular require considered harmful - /home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-openstack-0.1.25/lib/fog/compute/openstack/models/server.rb
	from ./example.rb:9:in  `<main>'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-core-1.45.0/lib/fog/core/service.rb:100:in  `new'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-core-1.45.0/lib/fog/core/service.rb:137:in  `setup_requirements'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-core-1.45.0/lib/fog/core/service.rb:274:in  `require_models'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-core-1.45.0/lib/fog/core/service.rb:274:in  `each'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-core-1.45.0/lib/fog/core/service.rb:274:in  `block in require_models'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-core-1.45.0/lib/fog/core/service.rb:324:in  `require_item'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-openstack-0.1.25/lib/fog/compute/openstack/models/server.rb:2:in  `<top (required)>'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-openstack-0.1.25/lib/fog/compute/openstack/models/metadata.rb:5:in  `<top (required)>'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
/home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-openstack-0.1.25/lib/fog/compute/openstack/models/server.rb:75: warning: method redefined; discarding old metadata
/home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-core-1.45.0/lib/fog/core/attributes/default.rb:52: warning: previous definition of metadata was here
/home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-openstack-0.1.25/lib/fog/compute/openstack/models/server.rb:82: warning: method redefined; discarding old metadata=
/home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-core-1.45.0/lib/fog/core/attributes/default.rb:43: warning: previous definition of metadata= was here
/home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-openstack-0.1.25/lib/fog/compute/openstack/models/server.rb:185: warning: method redefined; discarding old image_ref=
/home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-openstack-0.1.25/lib/fog/compute/openstack/models/server.rb:189: warning: method redefined; discarding old flavor_ref=
/home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-openstack-0.1.25/lib/fog/compute/openstack/models/flavor.rb:38: warning: method redefined; discarding old metadata
/home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-core-1.45.0/lib/fog/core/attributes/default.rb:52: warning: previous definition of metadata was here
/home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-openstack-0.1.25/lib/fog/compute/openstack/models/security_group.rb:14: warning: method redefined; discarding old security_group_rules
/home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-core-1.45.0/lib/fog/core/attributes/default.rb:52: warning: previous definition of security_group_rules was here
/home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-openstack-0.1.25/lib/fog/compute/openstack/models/key_pair.rb:15: warning: method redefined; discarding old public_key
/home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-core-1.45.0/lib/fog/core/attributes/default.rb:52: warning: previous definition of public_key was here
/home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-openstack-0.1.25/lib/fog/compute/openstack/models/key_pair.rb:15: warning: method redefined; discarding old public_key=
/home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-core-1.45.0/lib/fog/core/attributes/default.rb:43: warning: previous definition of public_key= was here
/home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-openstack-0.1.25/lib/fog/compute/openstack/models/host.rb:20: warning: method redefined; discarding old details
/home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-core-1.45.0/lib/fog/core/attributes/default.rb:52: warning: previous definition of details was here
/home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-openstack-0.1.25/lib/fog/compute/openstack/requests/delete_key_pair.rb:15: warning: method redefined; discarding old delete_key_pair
/home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-openstack-0.1.25/lib/fog/compute/openstack/requests/get_key_pair.rb:15: warning: previous definition of delete_key_pair was here
/home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-openstack-0.1.25/lib/fog/openstack/core.rb:176: warning: instance variable @openstack_management_url not initialized
/home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-openstack-0.1.25/lib/fog/openstack/core.rb:180: warning: instance variable @openstack_auth_token not initialized
/home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/excon-0.62.0/lib/excon.rb:118:in `new': Invalid URI: invalid (ArgumentError)
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-core-1.45.0/lib/fog/core/connection.rb:59:in `initialize'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-openstack-0.1.25/lib/fog/openstack.rb:415:in `new'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-openstack-0.1.25/lib/fog/openstack.rb:415:in `retrieve_tokens_v2'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-openstack-0.1.25/lib/fog/openstack.rb:193:in `authenticate_v2'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-openstack-0.1.25/lib/fog/openstack.rb:155:in `authenticate'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-openstack-0.1.25/lib/fog/openstack/core.rb:182:in `authenticate'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-openstack-0.1.25/lib/fog/compute/openstack.rb:397:in `initialize'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-core-1.45.0/lib/fog/core/service.rb:115:in `new'
	from /home/miha/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-core-1.45.0/lib/fog/core/service.rb:115:in `new'
	from ./example.rb:9:in `<main>'
```

PS: You are also correct that custom setters on fog-vcloud-director models bring bad UX. We're working on it, thanks for mentioning.

**Comment by plribeiro3000** [comment]
Well, thats because `fog-openstack` is doing the same thing.
See the DSL definition [here](https://github.com/fog/fog-openstack/blob/master/lib/fog/compute/openstack/models/server.rb#L15) and the method definition [here](https://github.com/fog/fog-openstack/blob/606d3f0bf78e85121dd86c565518b129863ba363/lib/fog/compute/openstack/models/server.rb#L75-L87)

Thats the first warning i saw in your backtrace but i'm pretty sure everything is the same.
