### ISSUE TITLE
JSON::ParserError

### ISSUE THREAD

**Issue by vadimstroganov** [fog/fog-core#247]
Hello! I use gem activestorage-openstack for Rails ActiveStorage, and have a problem (https://github.com/chaadow/activestorage-openstack/issues/25)

If I specify parameters that consist only of digits, I get an error:
```
Cannot load `Rails.config.active_storage.service`: JSON::ParserError
```
I found a line that creates this problem:

https://github.com/fog/fog-core/blob/master/lib/fog/core/service.rb#L166

Why is it necessary?

Trace:
```
multi_json (1.13.1) lib/multi_json/adapter.rb:20:in `load'
multi_json (1.13.1) lib/multi_json.rb:122:in `load'
fog-json (1.2.0) lib/fog/json.rb:40:in `decode'
fog-openstack (0.3.1) lib/fog/openstack/auth/token/v3.rb:52:in `set'
fog-openstack (0.3.1) lib/fog/openstack/auth/token.rb:35:in `initialize'
fog-openstack (0.3.1) lib/fog/openstack/auth/token.rb:21:in `new'
fog-openstack (0.3.1) lib/fog/openstack/auth/token.rb:21:in `build'
fog-openstack (0.3.1) lib/fog/openstack/core.rb:209:in `authenticate'
fog-openstack (0.3.1) lib/fog/openstack/core.rb:44:in `initialize'
fog-openstack (0.3.1) lib/fog/openstack/storage/storage.rb:117:in `initialize'
fog-core (2.1.2) lib/fog/core/service.rb:116:in `new'
fog-core (2.1.2) lib/fog/core/service.rb:116:in `new'
activestorage-openstack (0.5.0) lib/active_storage/service/open_stack_service.rb:12:in `initialize'
activestorage (5.2.1) lib/active_storage/service.rb:61:in `new'
activestorage (5.2.1) lib/active_storage/service.rb:61:in `build'
activestorage (5.2.1) lib/active_storage/service/configurator.rb:17:in `build'
activestorage (5.2.1) lib/active_storage/service/configurator.rb:8:in `build'
activestorage (5.2.1) lib/active_storage/service.rb:51:in `configure'
activestorage (5.2.1) lib/active_storage/engine.rb:90:in `block (2 levels) in <class:Engine>'
activesupport (5.2.1) lib/active_support/lazy_load_hooks.rb:71:in `instance_eval'
activesupport (5.2.1) lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
activesupport (5.2.1) lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
activesupport (5.2.1) lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
activesupport (5.2.1) lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
activesupport (5.2.1) lib/active_support/lazy_load_hooks.rb:51:in `each'
activesupport (5.2.1) lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
activestorage (5.2.1) app/models/active_storage/blob.rb:206:in `<class:Blob>'
activestorage (5.2.1) app/models/active_storage/blob.rb:16:in `<main>'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
activesupport (5.2.1) lib/active_support/dependencies.rb:472:in `block in load_file'
activesupport (5.2.1) lib/active_support/dependencies.rb:657:in `new_constants_in'
activesupport (5.2.1) lib/active_support/dependencies.rb:471:in `load_file'
activesupport (5.2.1) lib/active_support/dependencies.rb:369:in `block in require_or_load'
activesupport (5.2.1) lib/active_support/dependencies.rb:37:in `block in load_interlock'
activesupport (5.2.1) lib/active_support/dependencies/interlock.rb:14:in `block in loading'
activesupport (5.2.1) lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
activesupport (5.2.1) lib/active_support/dependencies/interlock.rb:13:in `loading'
activesupport (5.2.1) lib/active_support/dependencies.rb:37:in `load_interlock'
activesupport (5.2.1) lib/active_support/dependencies.rb:352:in `require_or_load'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:46:in `block in require_or_load'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:45:in `require_or_load'
activesupport (5.2.1) lib/active_support/dependencies.rb:506:in `load_missing_constant'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `block in load_missing_constant'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:57:in `load_missing_constant'
activesupport (5.2.1) lib/active_support/dependencies.rb:193:in `const_missing'
activesupport (5.2.1) lib/active_support/inflector/methods.rb:285:in `const_get'
activesupport (5.2.1) lib/active_support/inflector/methods.rb:285:in `block in constantize'
activesupport (5.2.1) lib/active_support/inflector/methods.rb:281:in `each'
activesupport (5.2.1) lib/active_support/inflector/methods.rb:281:in `inject'
activesupport (5.2.1) lib/active_support/inflector/methods.rb:281:in `constantize'
activesupport (5.2.1) lib/active_support/inflector/methods.rb:326:in `safe_constantize'
activesupport (5.2.1) lib/active_support/dependencies.rb:584:in `safe_get'
activesupport (5.2.1) lib/active_support/dependencies.rb:615:in `safe_constantize'
activerecord (5.2.1) lib/active_record/inheritance.rb:189:in `block in compute_type'
activerecord (5.2.1) lib/active_record/inheritance.rb:188:in `each'
activerecord (5.2.1) lib/active_record/inheritance.rb:188:in `compute_type'
activerecord (5.2.1) lib/active_record/reflection.rb:422:in `compute_class'
activerecord (5.2.1) lib/active_record/reflection.rb:379:in `klass'
activerecord (5.2.1) lib/active_record/reflection.rb:615:in `automatic_inverse_of'
activerecord (5.2.1) lib/active_record/reflection.rb:603:in `block in inverse_name'
activerecord (5.2.1) lib/active_record/reflection.rb:603:in `fetch'
activerecord (5.2.1) lib/active_record/reflection.rb:603:in `inverse_name'
activerecord (5.2.1) lib/active_record/reflection.rb:523:in `has_inverse?'
activerecord (5.2.1) lib/active_record/reflection.rb:239:in `check_validity_of_inverse!'
activerecord (5.2.1) lib/active_record/reflection.rb:474:in `check_validity!'
activerecord (5.2.1) lib/active_record/associations/association.rb:26:in `initialize'
activerecord (5.2.1) lib/active_record/associations.rb:237:in `new'
activerecord (5.2.1) lib/active_record/associations.rb:237:in `association'
activerecord (5.2.1) lib/active_record/associations/builder/association.rb:108:in `blob'
activesupport (5.2.1) lib/active_support/core_ext/module/delegation.rb:267:in `respond_to_missing?'
activemodel (5.2.1) lib/active_model/attribute_methods.rb:447:in `respond_to?'
activemodel (5.2.1) lib/active_model/attribute_methods.rb:447:in `respond_to?'
activerecord (5.2.1) lib/active_record/attribute_methods.rb:271:in `respond_to?'
activesupport (5.2.1) lib/active_support/core_ext/module/delegation.rb:271:in `method_missing'
app/views/pages/index.html.erb:11:in `_app_views_pages_index_html_erb__182532305373111792_70322993436320'
actionview (5.2.1) lib/action_view/template.rb:159:in `block in render'
activesupport (5.2.1) lib/active_support/notifications.rb:170:in `instrument'
actionview (5.2.1) lib/action_view/template.rb:354:in `instrument_render_template'
actionview (5.2.1) lib/action_view/template.rb:157:in `render'
actionview (5.2.1) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
actionview (5.2.1) lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument'
activesupport (5.2.1) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.1) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.1) lib/active_support/notifications.rb:168:in `instrument'
actionview (5.2.1) lib/action_view/renderer/abstract_renderer.rb:43:in `instrument'
actionview (5.2.1) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
actionview (5.2.1) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
actionview (5.2.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
jb (0.5.0) lib/jb/action_view_monkeys.rb:47:in `render_template'
actionview (5.2.1) lib/action_view/renderer/template_renderer.rb:16:in `render'
actionview (5.2.1) lib/action_view/renderer/renderer.rb:44:in `render_template'
actionview (5.2.1) lib/action_view/renderer/renderer.rb:25:in `render'
actionview (5.2.1) lib/action_view/rendering.rb:103:in `_render_template'
actionpack (5.2.1) lib/action_controller/metal/streaming.rb:219:in `_render_template'
actionview (5.2.1) lib/action_view/rendering.rb:84:in `render_to_body'
actionpack (5.2.1) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (5.2.1) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
actionpack (5.2.1) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (5.2.1) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
activesupport (5.2.1) lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
/Users/stroganov/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
activesupport (5.2.1) lib/active_support/core_ext/benchmark.rb:14:in `ms'
actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:46:in `block in render'
actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (5.2.1) lib/active_record/railties/controller_runtime.rb:31:in `cleanup_view_runtime'
actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:45:in `render'
actionpack (5.2.1) lib/action_controller/metal/implicit_render.rb:35:in `default_render'
actionpack (5.2.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
actionpack (5.2.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `tap'
actionpack (5.2.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (5.2.1) lib/abstract_controller/base.rb:194:in `process_action'
actionpack (5.2.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.2.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (5.2.1) lib/active_support/callbacks.rb:132:in `run_callbacks'
actionpack (5.2.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.1) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.1) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.1) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.1) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
activerecord (5.2.1) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
actionpack (5.2.1) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.1) lib/action_view/rendering.rb:32:in `process'
actionpack (5.2.1) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.1) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.1) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.1) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.1) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:840:in `call'
rack (2.0.6) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.6) lib/rack/etag.rb:25:in `call'
rack (2.0.6) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.6) lib/rack/head.rb:12:in `call'
actionpack (5.2.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.6) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.6) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/cookies.rb:670:in `call'
activerecord (5.2.1) lib/active_record/migration.rb:559:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.1) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.6) lib/rack/method_override.rb:22:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
rack-cors (1.0.2) lib/rack/cors.rb:97:in `call'
webpacker (3.5.5) lib/webpacker/dev_server_proxy.rb:22:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (5.2.1) lib/rails/engine.rb:524:in `call'
puma (3.12.0) lib/puma/configuration.rb:225:in `call'
puma (3.12.0) lib/puma/server.rb:658:in `handle_request'
puma (3.12.0) lib/puma/server.rb:472:in `process_client'
puma (3.12.0) lib/puma/server.rb:332:in `block in run'
puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```

**Comment by tokengeek** [comment]
I seem to recall this being spotted before but I can't find an issue across all the fog projects.

As the name `coerce_options` suggests it takes a Hash and converts all the values to underlying Ruby types. So a username that is only numbers is converted to a number.

So that is working as intended in case a configuration setting was a number (retries, ram required or similar numbers).

I think a `to_s` is required in `fog-openstack` after the configuration is parsed if they go on to assume that the username is always a String.

Otherwise there will be a change in the behaviour by adding support to whitelist/blacklist keys that shouldn't be changed when a service is loaded.

https://github.com/fog/fog-openstack/blob/master/lib/fog/openstack/storage.rb#L117 is just calling `super` so it looks like it is trying to authenticate using a number in the JSON.

So the value of username should be corrected before the authentication request.

I suspect the response from Openstack is not actually sending valid JSON? It may be that the JSON parse error is because it is returning an error used by not sending a string in.

**Comment by vadimstroganov** [comment]
I played around with debugger a bit and saw that the JSON::ParserError error is called after calling the authentication OpenStack API. If an number rather than a string is sent to the OpenStack API, the response body becomes an empty string.

Here response.body = "", this causes an error
https://github.com/fog/fog-openstack/blob/master/lib/fog/openstack/auth/token/v3.rb#L58
